#!/bin/bash

#
# ldall, high level script to setup and run ldall.sh
#
PATH=${PATH}:.

if [[ ! -d ldall-install ]]; then
	echo "ldall: can not find ldall-install"
	exit 1
fi

cd ldall-install; exec ./ldall.sh

