#!/bin/bash

#
# stf-client: run the stf client...
#
if [[ ${#JAVA_HOME} == 0 ]]; then
    echo "stf-client: JAVA_HOME must be set"
    exit 1
fi

jbin=${JAVA_HOME}/bin

#
# set the classpath from the jars in the jars
# directory...
#
cp=`/usr/bin/lessecho ./jars/*.jar | tr ' ' ':' | sed 's/:$//1'`

#
# run stf...
#
exec ${jbin}/java -classpath "${cp}" icecube.daq.stf.STF $*

