#!/bin/bash

#
# stf-client: run the stf client...
#
if [[ ${#JAVA_HOME} == 0 ]]; then
    echo "stf-client: JAVA_HOME must be set"
    exit 1
fi

jbin=${JAVA_HOME}/bin

#
# set the classpath from the jars in the jars
# directory...
#
cp=`/usr/bin/lessecho ./jars/*.jar | tr ' ' ':' | sed 's/:$//1'`

#
# make sure rmiregistry is running
#
rmir=`pgrep rmiregistry`
if [[ ${#rmir} == 0 ]]; then
    echo "stf-client starting rmiregistry..."
    ${jbin}/rmiregistry &

    sleep 2
    ${jbin}/java -classpath "${cp}" icecube.daq.domhub.DOMHub >& /tmp/dh.log &
    sleep 4
fi

#
# run stf...
#
exec ${jbin}/java -classpath "${cp}" icecube.daq.stf.STF $*

